### ISSUE TITLE
Add Support for ESM

### ISSUE THREAD

**Issue by SellersEvan** [offen/esbuild-plugin-jsonschema#7]
Could we add support full support for ESM? I believe this article walks through how to set up support for both ESM and CJS.
https://dev.to/snyk/building-an-npm-package-compatible-with-esm-and-cjs-in-2024-88m

I would be happy to do make the updates if someone on the team can merge it.

**Comment by m90** [comment]
I do work in other ecosystems mostly nowadays, so I am not really in the loop when it comes to the current state of the CommonJS to ESM transition in runtimes, but in case support for ESM can be added without breaking anything for existing CommonJS consumers (hint: it's me :) ), I don't see any reason not to do this.

If you want to open a PR that adds this, I'm happy to review and merge.

**Comment by SellersEvan** [comment]
Turns out I had a configuration setup incorrectly. ESM can import CJS but not the other way around, so I don't believe any changes need to be made. Sorry for the confusion. I am closing the issue.
